// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRA5y_n7yZcthH8LWc7ivY2fn7O9lrHY4',
    appId: '1:958518376868:web:9dfa648c2cd41927a7e931',
    messagingSenderId: '958518376868',
    projectId: 'knue-mate',
    authDomain: 'knue-mate.firebaseapp.com',
    storageBucket: 'knue-mate.firebasestorage.app',
    measurementId: 'G-0PF25FY1FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJpxu6_bAVcMr5i5NobtFm24_OhVzB6o',
    appId: '1:958518376868:android:b5725c86521d1a2aa7e931',
    messagingSenderId: '958518376868',
    projectId: 'knue-mate',
    storageBucket: 'knue-mate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsl3F4rPBWPjSBD8Ine-rjca2IBotq01o',
    appId: '1:958518376868:ios:b699680e96ba4757a7e931',
    messagingSenderId: '958518376868',
    projectId: 'knue-mate',
    storageBucket: 'knue-mate.firebasestorage.app',
    iosBundleId: 'com.knue.knuemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsl3F4rPBWPjSBD8Ine-rjca2IBotq01o',
    appId: '1:958518376868:ios:4e444951ed7187caa7e931',
    messagingSenderId: '958518376868',
    projectId: 'knue-mate',
    storageBucket: 'knue-mate.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRA5y_n7yZcthH8LWc7ivY2fn7O9lrHY4',
    appId: '1:958518376868:web:382b721634cb6678a7e931',
    messagingSenderId: '958518376868',
    projectId: 'knue-mate',
    authDomain: 'knue-mate.firebaseapp.com',
    storageBucket: 'knue-mate.firebasestorage.app',
    measurementId: 'G-11BQQSRBHS',
  );

}